Add initial client
yeti-platform/goyeti pull request #1
Opened 2024-10-04 16:56 UTC by daisukixci

The client is capable of authenticating, manually crafted search and do basic observable search

2024-10-05 09:16 UTC, tomchop requested changes

2024-10-05 09:16 UTC, tomchop commented on examples/main.go
> +	"github.com/daisukixci/goyeti"
Can we update this to point to the `yeti-patform/goyeti` now or do we have to wait for it to be merged first?

2024-10-05 09:16 UTC, tomchop commented on client.go
> +	"github.com/daisukixci/goyeti/models"
Update here too

2024-10-07 16:21 UTC, daisukixci commented on examples/main.go
> +	"github.com/daisukixci/goyeti"
Yes it was a copy of what I did before the repo was created. I fixed it now

2024-10-07 16:21 UTC, daisukixci commented on client.go
> +	"github.com/daisukixci/goyeti/models"
fixed

2024-10-07 17:17 UTC, daisukixci commented on client_test.go
I need to finish the test

2024-10-18 06:56 UTC, udgover approved these changes
LGTM! Thanks for this contribution!

2024-10-18 06:56 UTC, merged